
package com.wty.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceHello", targetNamespace = "http://service.wty.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceHello {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "startRedis", targetNamespace = "http://service.wty.com/", className = "com.wty.client.StartRedis")
    @ResponseWrapper(localName = "startRedisResponse", targetNamespace = "http://service.wty.com/", className = "com.wty.client.StartRedisResponse")
    @Action(input = "http://service.wty.com/ServiceHello/startRedisRequest", output = "http://service.wty.com/ServiceHello/startRedisResponse")
    public void startRedis();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "hash_get")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hash_get", targetNamespace = "http://service.wty.com/", className = "com.wty.client.HashGet")
    @ResponseWrapper(localName = "hash_getResponse", targetNamespace = "http://service.wty.com/", className = "com.wty.client.HashGetResponse")
    @Action(input = "http://service.wty.com/ServiceHello/hash_getRequest", output = "http://service.wty.com/ServiceHello/hash_getResponse")
    public String hashGet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "hash_set")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hash_set", targetNamespace = "http://service.wty.com/", className = "com.wty.client.HashSet")
    @ResponseWrapper(localName = "hash_setResponse", targetNamespace = "http://service.wty.com/", className = "com.wty.client.HashSetResponse")
    @Action(input = "http://service.wty.com/ServiceHello/hash_setRequest", output = "http://service.wty.com/ServiceHello/hash_setResponse")
    public Long hashSet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hincre", targetNamespace = "http://service.wty.com/", className = "com.wty.client.Hincre")
    @ResponseWrapper(localName = "hincreResponse", targetNamespace = "http://service.wty.com/", className = "com.wty.client.HincreResponse")
    @Action(input = "http://service.wty.com/ServiceHello/hincreRequest", output = "http://service.wty.com/ServiceHello/hincreResponse")
    public Long hincre(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @return
     *     returns com.wty.client.Transaction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multi", targetNamespace = "http://service.wty.com/", className = "com.wty.client.Multi")
    @ResponseWrapper(localName = "multiResponse", targetNamespace = "http://service.wty.com/", className = "com.wty.client.MultiResponse")
    @Action(input = "http://service.wty.com/ServiceHello/multiRequest", output = "http://service.wty.com/ServiceHello/multiResponse")
    public Transaction multi();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "flushDB", targetNamespace = "http://service.wty.com/", className = "com.wty.client.FlushDB")
    @ResponseWrapper(localName = "flushDBResponse", targetNamespace = "http://service.wty.com/", className = "com.wty.client.FlushDBResponse")
    @Action(input = "http://service.wty.com/ServiceHello/flushDBRequest", output = "http://service.wty.com/ServiceHello/flushDBResponse")
    public String flushDB();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectDB", targetNamespace = "http://service.wty.com/", className = "com.wty.client.SelectDB")
    @ResponseWrapper(localName = "selectDBResponse", targetNamespace = "http://service.wty.com/", className = "com.wty.client.SelectDBResponse")
    @Action(input = "http://service.wty.com/ServiceHello/selectDBRequest", output = "http://service.wty.com/ServiceHello/selectDBResponse")
    public String selectDB(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://service.wty.com/", className = "com.wty.client.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://service.wty.com/", className = "com.wty.client.GetResponse")
    @Action(input = "http://service.wty.com/ServiceHello/getRequest", output = "http://service.wty.com/ServiceHello/getResponse")
    public String get(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://service.wty.com/", className = "com.wty.client.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://service.wty.com/", className = "com.wty.client.GetValueResponse")
    @Action(input = "http://service.wty.com/ServiceHello/getValueRequest", output = "http://service.wty.com/ServiceHello/getValueResponse")
    public String getValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "set", targetNamespace = "http://service.wty.com/", className = "com.wty.client.Set")
    @ResponseWrapper(localName = "setResponse", targetNamespace = "http://service.wty.com/", className = "com.wty.client.SetResponse")
    @Action(input = "http://service.wty.com/ServiceHello/setRequest", output = "http://service.wty.com/ServiceHello/setResponse")
    public String set(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
